language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

services:
  - neo4j

install:
  - go get -t -d -v ./...
  - go get github.com/onsi/ginkgo/ginkgo

env:
  - NORM_NEO4J_URL=http://localhost:7474

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
